/* Dle-Arena Service Worker: lädt die Seite nach dem ersten Besuch sofort und funktioniert offline */
const V = "dle-1791534679", CORE = ["./", "index.html", "manifest.webmanifest"], ASSETS = ["data/r6icons.js", "fonts/archivo-black-latin-400-normal.woff2", "fonts/archivo-black-latin-ext-400-normal.woff2", "fonts/bangers-latin-400-normal.woff2", "fonts/bangers-latin-ext-400-normal.woff2", "fonts/chakra-petch-latin-500-normal.woff2", "fonts/chakra-petch-latin-600-normal.woff2", "fonts/chakra-petch-latin-700-normal.woff2", "fonts/chakra-petch-latin-ext-500-normal.woff2", "fonts/chakra-petch-latin-ext-600-normal.woff2", "fonts/chakra-petch-latin-ext-700-normal.woff2", "fonts/cinzel-latin-600-normal.woff2", "fonts/cinzel-latin-700-normal.woff2", "fonts/cinzel-latin-ext-600-normal.woff2", "fonts/cinzel-latin-ext-700-normal.woff2", "fonts/figtree-latin-400-normal.woff2", "fonts/figtree-latin-500-normal.woff2", "fonts/figtree-latin-600-normal.woff2", "fonts/figtree-latin-700-normal.woff2", "fonts/figtree-latin-ext-400-normal.woff2", "fonts/figtree-latin-ext-500-normal.woff2", "fonts/figtree-latin-ext-600-normal.woff2", "fonts/figtree-latin-ext-700-normal.woff2", "fonts/fredoka-latin-500-normal.woff2", "fonts/fredoka-latin-600-normal.woff2", "fonts/fredoka-latin-700-normal.woff2", "fonts/fredoka-latin-ext-500-normal.woff2", "fonts/fredoka-latin-ext-600-normal.woff2", "fonts/fredoka-latin-ext-700-normal.woff2", "fonts/jetbrains-mono-latin-500-normal.woff2", "fonts/jetbrains-mono-latin-ext-500-normal.woff2", "fonts/permanent-marker-latin-400-normal.woff2", "fonts/pirata-one-latin-400-normal.woff2", "fonts/pirata-one-latin-ext-400-normal.woff2", "fonts/pixelify-sans-latin-500-normal.woff2", "fonts/pixelify-sans-latin-700-normal.woff2", "fonts/pixelify-sans-latin-ext-500-normal.woff2", "fonts/pixelify-sans-latin-ext-700-normal.woff2", "fonts/rajdhani-latin-600-normal.woff2", "fonts/rajdhani-latin-700-normal.woff2", "fonts/rajdhani-latin-ext-600-normal.woff2", "fonts/rajdhani-latin-ext-700-normal.woff2", "fonts/shippori-mincho-b1-latin-700-normal.woff2", "fonts/shippori-mincho-b1-latin-800-normal.woff2", "fonts/shippori-mincho-b1-latin-ext-700-normal.woff2", "fonts/shippori-mincho-b1-latin-ext-800-normal.woff2", "img/bleach.webp", "img/clashroyale.webp", "img/dragonball.webp", "img/fortnite.webp", "img/lol.webp", "img/naruto.webp", "img/onepiece.webp", "img/pokemon.webp", "img/valab.webp", "img/valorant.webp", "js/arena.js", "js/chunk-WJOXSRKB.js", "js/lanes.js", "js/net.js", "js/netws.js", "js/turbo.js", "js/wild.js"];
self.addEventListener("install", e => { e.waitUntil(caches.open(V).then(c => c.addAll(CORE)).then(() => self.skipWaiting())); });
self.addEventListener("activate", e => { e.waitUntil(caches.keys().then(ks => Promise.all(ks.filter(k => k !== V).map(k => caches.delete(k)))).then(() => self.clients.claim())); });
self.addEventListener("fetch", e => {
  const u = new URL(e.request.url);
  if (e.request.method !== "GET" || u.origin !== location.origin) return;
  const isPage = e.request.mode === "navigate" || u.pathname.endsWith("/") || u.pathname.endsWith("index.html");
  if (isPage) { // Netzwerk zuerst, damit Updates sofort ankommen; offline aus dem Cache
    e.respondWith(fetch(e.request).then(r => { const cp = r.clone(); caches.open(V).then(c => c.put("index.html", cp)); return r; }).catch(() => caches.match("index.html")));
    return;
  }
  e.respondWith(caches.match(e.request).then(hit => hit || fetch(e.request).then(r => { if (r.ok) { const cp = r.clone(); caches.open(V).then(c => c.put(e.request, cp)); } return r; })));
});
